version: '3.1'
services:
  scheduler:
    networks:
    - airflow
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.6
    command: "--host 0.0.0.0 --port '8081' --scheme http"
    ports:
    - "8081:8081"
    - "50051:50051"
    volumes:
    - ${PWD}/include/weaviate/backup:/var/lib/weaviate/backup
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'readonlykey,adminkey'
      AUTHENTICATION_APIKEY_USERS: 'jane@doe.com,john@doe.com'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai, backup-filesystem, qna-openai, text2vec'
      BACKUP_FILESYSTEM_PATH: '/var/lib/weaviate/backup'
      CLUSTER_HOSTNAME: 'node1'
    networks:
    - airflow